### ISSUE TITLE
Create Basic Search Front End

### ISSUE THREAD

**Issue by noahzlutz** [ucsb-cs156-w22/team04-w22-7pm-courses#8]
There is already component that allows you to select a quarter from a dropdown menu; it appears in the Storybook and has full test coverage.

Add an additional component that allows you to select a level (UG-lower div, UG-upper div, grad, all). The levels can be hard coded.

You can use code from the S21 proj-ucsb-courses-search as a model.

For this story, the Search button only needs to bring up a toast that says: "If search were implemented, we would have made a call to the back end to get courses for x subject, x quarter, x level".

A later issue will hook this up to get the backend info.

DEFINE SUITABLE ACCEPTANCE CRITERIA

**Comment by ericxu002** [comment]
I need to create storybook, make sure test coverage exists, and this component exists in main also the utilities

EDIT NOTE: I actually don't need utilities because all utilities does is provide and export the helper functions which I don't need for a simple drop down menu.

**Comment by ericxu002** [comment]
Finished the level dropdown,

Now need to do make a button component that gives a toast upon click

**Comment by ericxu002** [comment]
alright I made the button component  but i can't check it in storybook because I can't see the toast (i tested this theory by running team03 which had a button create a toast upon succession of creating a ucsbsubject) so the only way to see the toast is to see some product on the local host website. regardless I believe that I met all the criteria within this issue and now I just peer review and potentailly a TA. NOTE: I do have 100% coverage and mutations killed.

**Comment by ericxu002** [comment]
Everything should be good and ready for merge once code review is performed.
